# 编译器
CXX = g++
# 编译选项
CXXFLAGS = -std=c++11 -Wall
# 目标可执行文件
TARGET = a.out
# 源文件
SRCS = main.cpp misc.cpp MemoryManager.cpp LinkedList.cpp degeneracy_helper.cpp degeneracy_algorithm_cliques_A.cpp bicliqueIndex.cpp
# 目标文件
OBJS = $(SRCS:.cpp=.o)

# 默认目标
all: $(TARGET)

# 生成可执行文件
$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(OBJS)

# 编译每个源文件为目标文件
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# 清理生成的文件
clean:
	rm -f $(OBJS) $(TARGET)